#!/usr/bin/env bash
# deploy/install.sh — bring ssl-manager up (or redeploy it) on an
# Ubuntu 24.04 server via Docker Compose.
#
# First run: installs Docker if it's missing, clones the repo, generates
# a .env with a real SESSION_SECRET, and starts the stack.
# Every later run: fetches the latest commit on BRANCH, rebuilds only
# what changed (backend/frontend images), and restarts the stack —
# postgres/vault are left running untouched unless their own config
# changed, so re-running this doesn't lose Vault's in-memory state by
# itself (see the durability note printed at the end, and the comment
# above the `vault` service in docker-compose.yml — a host reboot or
# `docker compose down` still would).
#
# Usage:
#   sudo ./install.sh                            # main -> /opt/ssl-manager
#   sudo BRANCH=my-branch ./install.sh           # deploy a different branch
#   sudo INSTALL_DIR=/srv/ssl-manager ./install.sh
#   sudo ENABLE_DEV_LOGIN=true ./install.sh      # first run only, see below
#
# Re-run this exact command after every push to redeploy.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/yilmazerhan/ssl-manager.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/ssl-manager}"
ENV_FILE="$INSTALL_DIR/.env"
# Only read on the very first run, when .env doesn't exist yet — see the
# .env generation step below. Ignored on every later run; edit .env
# directly to change it afterwards.
ENABLE_DEV_LOGIN="${ENABLE_DEV_LOGIN:-false}"

log()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARNING: %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

if [ "$(id -u)" -ne 0 ]; then
  die "run as root (sudo ./install.sh) — installing Docker and writing to $INSTALL_DIR both need it"
fi

# --- 1. Docker Engine + Compose plugin --------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine (official apt repo)"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg git
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  arch="$(dpkg --print-architecture)"
  # shellcheck disable=SC1091
  codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
  echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${codename} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
else
  log "Docker already installed ($(docker --version))"
  command -v git >/dev/null 2>&1 || { apt-get update -y && apt-get install -y git; }
fi

# --- 2. Clone or update the repo --------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Repo already present at $INSTALL_DIR — fetching $BRANCH"
  if [ -n "$(git -C "$INSTALL_DIR" status --porcelain)" ]; then
    warn "$INSTALL_DIR has local changes that are about to be discarded (this is a deploy checkout, not meant to be hand-edited):"
    git -C "$INSTALL_DIR" status --short
  fi
  git -C "$INSTALL_DIR" fetch origin "$BRANCH"
  git -C "$INSTALL_DIR" checkout "$BRANCH"
  git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
else
  log "Cloning $REPO_URL ($BRANCH) into $INSTALL_DIR"
  git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi

CURRENT_SHA="$(git -C "$INSTALL_DIR" rev-parse --short HEAD)"
log "Deploying $BRANCH @ $CURRENT_SHA"

# --- 3. .env: generated once on the first run, never touched again ---------
if [ ! -f "$ENV_FILE" ]; then
  log "First run — generating $ENV_FILE"
  session_secret="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# install.sh will never overwrite this file again — edit freely.

SESSION_SECRET=${session_secret}
DEV_AUTH_ENABLED=${ENABLE_DEV_LOGIN}

# Real login needs an OIDC provider. Until these are set, and while
# DEV_AUTH_ENABLED is false, nobody can sign in at all.
OIDC_ISSUER_URL=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_REDIRECT_URL=http://localhost:8080/auth/callback
FRONTEND_URL=http://localhost:5173

LETSENCRYPT_EMAIL=admin@example.com
ZEROSSL_API_KEY=
DNS01_PROVIDER=
CLOUDFLARE_DNS_API_TOKEN=

SMTP_ADDR=
SMTP_TO=
NOTIFY_WEBHOOK_URL=
EOF
  chmod 600 "$ENV_FILE"
else
  log "Using existing $ENV_FILE (left untouched)"
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a
if [ "${DEV_AUTH_ENABLED:-false}" != "true" ] && [ -z "${OIDC_ISSUER_URL:-}" ]; then
  warn "DEV_AUTH_ENABLED=false and OIDC_ISSUER_URL is empty in $ENV_FILE — nobody will be able to log in until you set OIDC_ISSUER_URL/OIDC_CLIENT_ID/OIDC_CLIENT_SECRET there, or set DEV_AUTH_ENABLED=true there as a stopgap."
fi

# --- 4. Build + (re)start ----------------------------------------------------
cd "$INSTALL_DIR"
log "Building and starting the stack"
docker compose --env-file "$ENV_FILE" up -d --build --remove-orphans

log "Waiting for the backend to report healthy"
healthy=false
for _ in $(seq 1 30); do
  if curl -fs http://localhost:8080/healthz >/dev/null 2>&1; then
    healthy=true
    break
  fi
  sleep 2
done

docker compose ps

if [ "$healthy" = true ]; then
  log "Deployed $BRANCH @ $CURRENT_SHA — backend is up"
else
  warn "Backend did not report healthy within 60s — it may still be starting. Check: docker compose -f $INSTALL_DIR/docker-compose.yml logs backend"
fi

cat <<EOF

Vault is running in dev mode (in-memory, no persistent storage) — see the
comment above the "vault" service in docker-compose.yml. That's fine for
now, but every certificate's private key material lives only in that
container's memory: a host reboot, a "docker compose down", or recreating
the vault container will permanently destroy it all. Move to a persistent
Vault backend before this server holds certificates you actually care about.
EOF
